# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
  use_frameworks!

target 'BlindSight' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks


  # Pods for BlindSight

  pod 'Firebase/Core'
  pod 'Firebase/Firestore'
	pod 'Firebase/Auth'
	pod 'TwilioVideo', '~> 2.10'
  pod 'GoogleMaps'
  pod 'GooglePlaces'
	
  target 'BlindSightTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'BlindSightUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
